version: '3.1'
services:
  router:
    image: docker.io/dockerklint/aim_router:v1.1
    container_name: router
    restart: always
    networks: 
      - aimnet
    ports:
      - "8100:8100"
    volumes:
      - ~/data/aim/:/data/
    environment:
      aim_CONSULURL: consul:8500
      aim_LOGLEVEL: INFO
  royal:
    image: docker.io/dockerklint/aim_royal:v1.4
    container_name: royal
    restart: always
    networks: 
      - aimnet
    ports:
      - "8080:8080"
    volumes:
      - ~/data/aim/:/data/
    environment:
      aim_PUBLICADDRESS: royal
      aim_CONSULURL: consul:8500
      aim_REDISADDRS: redis:6379
      aim_BASEDB: root:123456@tcp(mysql:3306)/aim_base?charset=utf8mb4&parseTime=True&loc=Local
      aim_MESSAGEDB: root:123456@tcp(mysql:3306)/aim_message?charset=utf8mb4&parseTime=True&loc=Local
      aim_LOGLEVEL: DEBUG
  gateway:
    image: docker.io/dockerklint/aim_gateway:v1.4
    container_name: wgateway
    restart: always
    networks: 
      - aimnet
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ~/data/aim/:/data/
    environment:
      aim_PUBLICADDRESS: gateway
      aim_CONSULURL: consul:8500
      aim_LOGLEVEL: DEBUG
      aim_TAGS: IDC:SH_ALI
      aim_DOMAIN: ws://119.3.4.216:8000
  server:
    image: docker.io/dockerklint/aim_server:v1.4
    container_name: chat
    restart: always
    networks: 
      - aimnet
    ports:
      - "8005:8005"
      - "8006:8006"
    volumes:
      - ~/data/aim/:/data/
    environment:
      aim_PUBLICADDRESS: server
      aim_CONSULURL: consul:8500
      aim_REDISADDRS: redis:6379
      aim_LOGLEVEL: DEBUG
      aim_ROYALURL: http://royal:8080
    dns: consul
networks:
  aimnet: {}